# Toolchain file for cross-compiling to ARM aarch64
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(TOOLCHAIN_PREFIX /usr/local/linaro-aarch64-2020.09-gcc10.2-linux5.4)
set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}/bin/aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}/bin/aarch64-linux-gnu-g++)
set(CMAKE_FIND_ROOT_PATH ${TOOLCHAIN_PREFIX}/aarch64-linux-gnu)
set(CMAKE_SYSROOT ${TOOLCHAIN_PREFIX}/aarch64-linux-gnu/libc)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
